In [1]:
#create two matrices using nested list
matrix1=[
    [1,2,3],
    [4,5,6]
]
matrix2=[
    [7,8,9],
    [10,11,12]
]
result=[
    [0,0,0],
    [0,0,0]
]
#Performing matrix addition
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j]=matrix1[i][j]+matrix2[i][j]

#Display the result
print("Matrix1:")
for row in matrix1:
    print(row)
    
print("Matrix2:")
for row in matrix2:
    print(row)

print("\nSum of matrix1 and matrix2:")
for row in result:
    print(row)

Matrix1:
[1, 2, 3]
[4, 5, 6]
Matrix2:
[7, 8, 9]
[10, 11, 12]

Sum of matrix1 and matrix2:
[8, 10, 12]
[14, 16, 18]


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
res=a+b
print(res)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
